### ISSUE TITLE
Cannot build lancoder - PoolTest.testDispatchingSingleWorker:98 null

### ISSUE THREAD

**Issue by skydiscover** [jdupl/lancoder#41]
Hi, I tried to build lancoder from Windows (with modification to the hardcoded paths in the tests) and Linux and it fails most of the time (95%) from tests in PoolTest : 
`Running org.lancoder.common.pool.PoolTest
Exception in thread "Thread-5" java.lang.NullPointerException
	at org.lancoder.common.pool.PoolWorker.run(PoolWorker.java:171)
	at java.lang.Thread.run(Thread.java:745)
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.056 sec <<< FAILURE! - in org.lancoder.common.pool.PoolTest
testDispatchingSingleWorker(org.lancoder.common.pool.PoolTest)  Time elapsed: 0.403 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.lancoder.common.pool.PoolTest.testDispatchingSingleWorker(PoolTest.java:98)
`

And even when I am lucky enough for it to pass the tests, I always get the NullPointerException.

**Comment by jdupl** [comment]
Hi,

To avoid tests, you can build and skip unit tests with maven `mvn clean package -Dmaven.test.skip=true`

The unit tests run 100% for me on Linux. The null pointer is not a real issue. It is only that no listener was passed to the worker (test is not supposed to fail for this reason).
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.lancoder.common.utils.TestTimeUtils
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 sec - in org.lancoder.common.utils.TestTimeUtils
Running org.lancoder.common.math.average.timed.TimedMovingAverageTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.lancoder.common.math.average.timed.TimedMovingAverageTest
Running org.lancoder.common.pool.PoolTest
Exception in thread "Thread-4" java.lang.NullPointerException
	at org.lancoder.common.pool.PoolWorker.run(PoolWorker.java:171)
	at java.lang.Thread.run(Thread.java:745)
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.976 sec - in org.lancoder.common.pool.PoolTest
Running org.lancoder.common.MkvMergeMuxerTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.877 sec - in org.lancoder.common.MkvMergeMuxerTest
Running org.lancoder.common.JobDispatchingTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.788 sec - in org.lancoder.common.JobDispatchingTest
Running org.lancoder.common.scheduler.SchedulerTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.414 sec - in org.lancoder.common.scheduler.SchedulerTest
Running org.lancoder.common.JobInstanciationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.393 sec - in org.lancoder.common.JobInstanciationTest
Running org.lancoder.common.codecs.TestCodecLoader
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.lancoder.common.codecs.TestCodecLoader

Results :

Tests run: 27, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.234 s
[INFO] Finished at: 2016-05-14T12:42:10-04:00
[INFO] Final Memory: 25M/309M
[INFO] ------------------------------------------------------------------------

```


However, I am investigating why this test `org.lancoder.common.pool.PoolTest.testDispatchingSingleWorker(PoolTest.java:98)` fails.
