### ISSUE TITLE
worker crash when launched with verbose level 5+

### ISSUE THREAD

**Issue by skydiscover** [jdupl/lancoder#43]
Hi, I noticed that when launched with `-w -vvvvv` or `-w -vvvvvv`, lancoder crashed, it only happens with the worker.

Here is the log : 
```
e:\#Download>java -jar lancoder-0.4.0-jar-with-dependencies.jar -w -vvvvv
Sat May 21 14:55:25 CEST 2016 INFO: Runnning lancoder 0.4.0
Sat May 21 14:55:25 CEST 2016 FINE: Loaded config from disk.
Sat May 21 14:55:25 CEST 2016 FINE: Detected 8 threads available.
Sat May 21 14:55:25 CEST 2016 FINER: [C:\Program Files (x86)\ffmpeg\bin\ffmpeg.exe, -encoders]
Exception in thread "main" java.lang.NullPointerException
        at org.lancoder.worker.Worker.getStatus(Worker.java:258)
        at org.lancoder.worker.logging.LogSenderPool.isOnline(LogSenderPool.java:27)
        at org.lancoder.common.logging.ClusterLogStagingHandler.flush(ClusterLogStagingHandler.java:29)
        at org.lancoder.common.logging.ClusterLogStagingHandler.publish(ClusterLogStagingHandler.java:24)
        at java.util.logging.Logger.log(Unknown Source)
        at java.util.logging.Logger.doLog(Unknown Source)
        at java.util.logging.Logger.log(Unknown Source)
        at java.util.logging.Logger.finer(Unknown Source)
        at org.lancoder.ffmpeg.FFmpegReader.read(FFmpegReader.java:65)
        at org.lancoder.ffmpeg.FFmpegReader.read(FFmpegReader.java:37)
        at org.lancoder.ffmpeg.probers.CodecProber.getNodeCapabilities(CodecProber.java:29)
        at org.lancoder.ffmpeg.FFmpegWrapper.getAvailableCodecs(FFmpegWrapper.java:19)
        at org.lancoder.worker.Worker.bootstrap(Worker.java:83)
        at org.lancoder.Main.run(Main.java:122)
        at org.lancoder.Main.main(Main.java:38)
Exception in thread "Thread-1" java.lang.NullPointerException
        at org.lancoder.common.network.cluster.Server.stop(Server.java:28)
        at org.lancoder.common.Container.stopServices(Container.java:98)
        at org.lancoder.common.Container.stop(Container.java:107)
        at org.lancoder.worker.Worker.shutdown(Worker.java:126)
        at org.lancoder.Main$1.run(Main.java:115)
```

**Comment by jdupl** [comment]
Fixed it was only a null pointer
